boakfriends/hammeroids

.gitignore

Adds `.byebug_history` to `.gitignore`
No need to check this in.

ignore byebug history

---

app/assets/js/GameState.js
app/assets/js/Sockets.js
app/views/game.erb
config.ru

Comments out any mention of sockets
Console errors were popping up and puma wouldn't start

Commented out all mention of sockets until we have another solution

---

app/assets/js/Game.js

Makes the play area bigger and changes how the context is gotten (no longer on every loop)
Needed doing

Made the play area bigger, changed how we get context

---

app/app.rb
app/assets/js/GameState.js
app/assets/js/Sockets.js
app/assets/js/creator/creator.js
app/assets/js/creator/drawer.js
app/views/creator.erb
app/views/game.erb
config.ru

Adds an "entity creator" at /creator (doesn't actually create anything, just gives coords for drawing stuff)
I wanted to draw something to put in the game

Entity creator

---

package-lock.json

Updates package lock missed in #37

Update missed package lock after npm install.

---

.travis.yml

Runs the Mocha tests in CI.
Needed to install npm dependencies before running.

Run NPM tests in Travis

---

app/javascript/src/game/drawing/textdrawer.js
app/javascript/src/game/entities/ship.js
app/javascript/src/game/entities/slug.js
app/javascript/src/game/gamestate.js
app/javascript/src/game/input/input.js
app/javascript/src/game/view.js
app/javascript/src/main.js
app/lib/player.rb
app/views/game.erb
spec/requests/app_controller_spec.rb
test/drawing/test_textdrawer.js
test/test_view.js

Adds name display to game area on button press 'z'
Thought it would be cool.
app/lib/player.rb - not sure if this is the correct way to do this
Press 'z'

Adding text display. Press 'z' to show player name

---

app/app.rb
app/assets/styles/normalize.css
app/assets/styles/skeleton.css
app/views/creator.erb
app/views/game.erb
app/views/join.erb
app/views/layout/css.erb

Closes https://github.com/boakfriends/hammeroids/issues/52
Adds a helper to render partial ERBs and cut down on duplication of common layout code.
Adds Skeleton CSS: http://getskeleton.com/
Includes a partial with Skeleton CSS in all views.

Add skeleton css

---

app/views/game.erb
app/views/join.erb

Adds some basic layout to join and game views.

Add basic grid

---

app/app.rb
app/javascript/src/game/drawing/pathdrawer.js
app/javascript/src/game/entities/ship.js
app/javascript/src/game/entities/slug.js
app/javascript/src/game/gamestate.js
app/javascript/src/game/physics/physics.js
app/javascript/src/game/sockets/sockets.js
app/lib/connection.rb
test/entities/test_ship.js
test/physics/test_physics.js
test/sockets/test_sockets.js

Adds basic broadcast functionality to the app.
Making the game multiplayer using EventMachine
connector.rb - has no tests...not sure how to test :(
Play the game, load a new player in a new browser tab

Added basic broadcast functionality to app.

---

app/javascript/src/game/app.js
app/javascript/src/game/drawing/pathdrawer.js
app/javascript/src/game/drawing/textdrawer.js
app/javascript/src/game/entities/ship.js
app/javascript/src/game/entities/slug.js
app/javascript/src/game/gamestate.js
app/javascript/src/game/input/input.js
app/javascript/src/game/physics/physics.js
app/javascript/src/game/sockets/sockets.js
app/javascript/src/game/view.js
test/entities/test_ship.js

Changes functions that do not have to be fat-arrow functions to normal functions.
Removes unnecessary underscore (_) from 'private' class properties.
My poor understanding of class functions.
All tests run, game works.

Changed all class functions to 'proper' functions

---

app/javascript/src/game/ui/lobby.js

Use const in lobby object

---

package-lock.json

package-lock updated

---

app/lib/lobby.rb

Removes hardcoding of class name in Hash.

Dynamically provide class name in JSON.

---

.gitignore
package-lock.json
package.json

Adds JS test coverage with Istanbul: https://istanbul.js.org
Currently set up to provide HTML output at: coverage/
Wanted to see how much we are covering.
package.json -> added istanbul to dev dependencies and to the test script
npm test
check coverage in coverage/ folder

Added istanbul for test coverage

---

app/lib/lobby.rb

Reverts boakfriends/hammeroids#81
Doesn't actually work.

Revert "Dynamically provide class name in JSON."

---

app/javascript/src/game/camera/camera.js
app/javascript/src/game/camera/delta.js
app/javascript/src/game/drawing/particledrawer.js
app/javascript/src/game/entities/dustparticle.js
app/javascript/src/game/gamestate.js
app/javascript/src/game/view.js
app/javascript/src/main.js
test/camera/test_camera.js
test/camera/test_delta.js
test/entities/test_dustparticle.js
test/test_view.js

Adds a camera and dust particles to the game.
The 'camera' just sets a transform on the context every time the view is updated based on the location of the ship (minus a delta to represent movement).
This makes the playable arena much larger, it allows players to go "outside the screen".
camera.js - most of the logic happens here
run the game

Added a camera and space dust particles

---

app/javascript/src/game/gamestate.js
app/javascript/src/game/view.js
app/javascript/src/main.js
test/test_gamestate.js
test/test_view.js

DOM elements are no longer passed to the constructor of gamestate
Cleaning up gamestate.js

Changed usage of global document. The gamestate object now caches it.

---

app/javascript/src/game/sockets/sockets.js

Makes sure we only draw local slugs
Slugs were being drawn twice

Only drawing local slugs - not network

---

app/javascript/src/game/sockets/message_router.js
app/javascript/src/game/sockets/messages/munitions.js
app/javascript/src/game/sockets/messages/player_name.js
app/javascript/src/game/sockets/messages/update.js
app/javascript/src/game/sockets/sockets.js
app/javascript/src/game/ui/lobby.js
app/lib/channels/subscription.rb
test/sockets/test_update.js
test/ui/test_lobby.js

Welcome message also send a payload with the player id.
Adds individual classes for dealing with network messages from the socket.
Sockets class was getting untidy
socket.js <- removed all the if statements from update method. Moved player_name into message router
update.js <- just updates the network ship
munitions.js <- probably we'll be adding lots of different types of munitions eventually
message_router.js <- added update, munitions and player_name
Fixes #70

Tidying sockets class - moved everything to its own message class.
